name: Docker run images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: run  Docker image
      run: docker run -d --name shop -p 8070:8070 karthik142/shopping-cart:latest

    - name: Get Container IP
      run: |
        echo "Container IP: $(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' shop)"
    - name: docker logs
      run: docker logs shop
    - name: docker status
      run: docker ps -a -s

    - name: Clean Up
      run: |
        docker stop shop
        docker rm shop

    - name: publicip
      run: curl ifconfig.me



    # - name: Install Ngrok
    #   run: |
    #     curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /usr/local/bin/ngrok.asc
    #     sudo apt-get install -y wget unzip
    #     wget https://github.com/ngrok/ngrok/releases/latest/download/ngrok-stable-linux-amd64.zip -O ngrok.zip
    #     unzip ngrok.zip
    #     sudo mv ngrok /usr/local/bin
    #     sudo chmod +x /usr/local/bin/ngrok

    #     sleep 10  # Wait for Ngrok to start
    #     curl -s http://localhost:4040/api/tunnels | jq -r .tunnels[0].public_url
